# Generated by Django 4.2.4 on 2023-08-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.UUIDField(primary_key=True, serialize=False)),
                ('admin_number', models.CharField(max_length=50)),
                ('admin_username', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.UUIDField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('student_id', models.UUIDField(primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=50)),
                ('student_username', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('user_role_id', models.UUIDField(primary_key=True, serialize=False)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.roles')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('student_profile_id', models.UUIDField(primary_key=True, serialize=False)),
                ('student_last_name', models.CharField(max_length=50)),
                ('student_first_name', models.CharField(max_length=50)),
                ('student_middle_name', models.CharField(max_length=50)),
                ('student_full_name', models.CharField(max_length=50)),
                ('student_program', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=50)),
                ('student_contact', models.IntegerField()),
                ('student_birthday', models.DateField()),
                ('student_gender', models.CharField(max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRoles',
            fields=[
                ('admin_role_id', models.UUIDField(primary_key=True, serialize=False)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.admin')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.roles')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('admin_profile_id', models.UUIDField(primary_key=True, serialize=False)),
                ('admin_last_name', models.CharField(max_length=50)),
                ('admin_first_name', models.CharField(max_length=50)),
                ('admin_middle_name', models.CharField(max_length=50)),
                ('admin_full_name', models.CharField(max_length=50)),
                ('admin_gender', models.CharField(max_length=10)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.admin')),
            ],
        ),
    ]
