# Generated by Django 4.2.4 on 2023-08-28 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.UUIDField(primary_key=True, serialize=False)),
                ('adminNumber', models.CharField(max_length=50)),
                ('adminUsername', models.CharField(max_length=50)),
                ('adminPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleId', models.UUIDField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('studentId', models.UUIDField(primary_key=True, serialize=False)),
                ('studentNumber', models.CharField(max_length=50)),
                ('studentUsername', models.CharField(max_length=50)),
                ('studentPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('userRoleId', models.UUIDField(primary_key=True, serialize=False)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.roles')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('studentProfileId', models.UUIDField(primary_key=True, serialize=False)),
                ('studentLastName', models.CharField(max_length=50)),
                ('studentFirstName', models.CharField(max_length=50)),
                ('studentMiddleName', models.CharField(max_length=50)),
                ('studentFullName', models.CharField(max_length=50)),
                ('studentProgram', models.CharField(max_length=50)),
                ('studentEmail', models.CharField(max_length=50)),
                ('studentContact', models.IntegerField()),
                ('studentBirthday', models.DateField()),
                ('studentGender', models.CharField(max_length=10)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRoles',
            fields=[
                ('adminRoleId', models.UUIDField(primary_key=True, serialize=False)),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.admin')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.roles')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('adminProfileId', models.UUIDField(primary_key=True, serialize=False)),
                ('adminLastName', models.CharField(max_length=50)),
                ('adminFirstName', models.CharField(max_length=50)),
                ('adminMiddleMame', models.CharField(max_length=50)),
                ('adminFullName', models.CharField(max_length=50)),
                ('adminGender', models.CharField(max_length=10)),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupweb.admin')),
            ],
        ),
    ]
